name: 'GetIDToken'
description: 'Get ID token from Github OIDC provider'
inputs:
  deployment_type:  
    description: 'deployment type'
    required: true
  factory_cluster:  
    description: 'factory cluster'
    required: true
  deployment_path:  
    description: 'deployment path'
    required: true
outputs:
  id_token1: 
    description: 'ID token obtained from OIDC provider'
  id_token2: 
    description: 'ID token obtained from OIDC provider'
runs:
  using: 'node12'
  main: 'dist/index.js'